rm(list=ls())
setwd("C:\\Users\\mmorelli\\Google Drive\\Data Science\\04 - Exploratory Data Analysis")
source("./Project 02/ExDataPlotting2/plot1.R", chdir=TRUE)
rm(list=ls())
setwd("C:\\Users\\mmorelli\\Google Drive\\Data Science\\04 - Exploratory Data Analysis")
source("./Project 02/ExDataPlotting2/plot2.R", chdir=TRUE)
rm(list=ls())
setwd("C:\\Users\\mmorelli\\Google Drive\\Data Science\\04 - Exploratory Data Analysis")
source("./Project 02/ExDataPlotting2/plot3.R", chdir=TRUE)
rm(list=ls())
setwd("C:\\Users\\mmorelli\\Google Drive\\Data Science\\04 - Exploratory Data Analysis")
source("./Project 02/ExDataPlotting2/plot4.R", chdir=TRUE)
rm(list=ls())
setwd("C:\\Users\\mmorelli\\Google Drive\\Data Science\\04 - Exploratory Data Analysis")
source("./Project 02/ExDataPlotting2/plot5.R", chdir=TRUE)
rm(list=ls())
setwd("C:\\Users\\mmorelli\\Google Drive\\Data Science\\04 - Exploratory Data Analysis")
source("./Project 02/ExDataPlotting2/plot6.R", chdir=TRUE)
